on: [push]

defaults:
  run:
    shell: powershell

jobs:
  output:
    runs-on: windows-latest
    steps:
      - run:  |
          chcp 1252
          echo 'aäoöuü'
          $umlaut = 'aäoöuü'
          chcp 1252
          echo 'aäoöuü'
          echo $umlaut 
          $umlaut > out.txt
          cat out.txt
          chcp 850
          echo 'aäoöuü'
          echo $umlaut 
          $umlaut > out.txt
          cat out.txt
